version: "3.9"

services:
  mysql:
    container_name: "mysql_server1"
    image: mysql:8.0.26
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: cxl123
      MYSQL_DATABASE: django-project
      MYSQL_PASSWORD: cxl123
      MYSQL_PORT: 3306
    ports:
      - "3310:3306"
  web:
    container_name: "web_server1"
    build: .
    command: python3 manage.py runserver 0.0.0.0:8888
    volumes:
      - .:/code
    ports:
      - "80:8888"
    depends_on:
      - mysql
    restart: always

volumes:
  db_data: {}
